package testDataType;

public class PersonalaDetailsDataEntryTestdata {

	public String Users;
	public String CustType;  
	public String CIFID;
	public String ApplicationNo;
	public String CustName;
	public String IDType;
	public String IDNo;
	public String MobileNo;
	public String Currentyear;
	public String Date;
	public String Month;
	public String year;
	public String EmailID;
	public String ApplicantType;
	public String Salutation;
	public String FirstName;
	public String MiddleName;
	public String LastName;
	public String FatherFirstName;
	public String FatherMiddleName;
	public String FatherLastName;
	public String SpouseFirstName;
	public String SpouseMiddleName;
	public String SpouseLastName;
	public String NoOfChildren;
	public String SpouseStatus;
	public String Gender;
	public String EduLevel;
	public String Maritalstatus;
	public String Nationality;
	public String Ethinicity;
	public String Religion;
	public String Residentalstatus;
	public String Language;
	public String NoOfDependents;
	public String MothersMaidenName;
	public String TypeofResidence;
	public String CategoryOfClient;
	public String Rating;
	public String Remarks;
	public String PhoneNumber;
	public String MobileNumberprimary;
	public String MobileNumbersecondary;
	public String EMAIL;
	public String PREFEREDCONTACTDETAILS;
	public String PREFEREDCONTACTMethod;
	public String ModifyApplicantType;
}
